### ISSUE TITLE
Add the user message in OpenLog Database's views

### ISSUE THREAD

**Issue by PhilippeArdit** [paulswithers/openlogjava#24]
In class OpenLogItem, I've added the two lines : 

After "rtitem.addNewLine();" : 
logDoc.replaceItemValue("LogMessage", "Message, greater than 32k, is stored inside.");

Before "logDoc.replaceItemValue("LogMessage", getMessage());" :
logDoc.replaceItemValue("LogErrorMessage", errMsg + " - " + getMessage()); 

![clipboard02](https://cloud.githubusercontent.com/assets/5666698/3699253/26740c98-13d1-11e4-8b48-d1784fbe2340.jpg)

**Comment by paulswithers** [comment]
For readability I've used first 100 characters + "..."
